### ISSUE TITLE
Issues with DRIVER_NAME=test in rebar.config

### ISSUE THREAD

**Issue by priestjim** [squidfunk/generic-linked-in-driver#5]
By leaving DRIVER_NAME=test defined inside the project's rebar.config, you override the dependent project's DRIVER_NAME flag and the driver is built with DRIVER_NAME=test instead of the actual project's driver name!

**Comment by squidfunk** [comment]
Sorry for coming back to you so late.

That's the name of the test driver. Building your own driver, you have to include the source from the deps directory in your own rebar config. See the docs for more information:
https://github.com/squidfunk/generic-linked-in-driver#as-a-dependency-via-rebar-recommended 

Does that solve your problem?

**Comment by priestjim** [comment]
No! If I follow the tutorial, the DRIVER_NAME definition in my rebar is not overriding the default one.

**Comment by squidfunk** [comment]
Okay, I found the reason. When using the linked in driver as a dependency, rebar compiles the test driver first using `-DDRIVER_NAME=test`. Later, when compiling your port driver, it doesn't recompile the object file for `gen_driver.c`, thus the driver name never gets set.

You can work around the issue by copying `c_src/gen_driver.{c,h}` from the linked in driver source directory in your own project and compiling those.

I will provide a fix and keep you updated.

**Comment by squidfunk** [comment]
The bug should be fixed with the last commit. The driver will now clean the compiled object files after compilation. Additionally I added the post hooks to the specs for building the driver, which should also be included in your custom rebar file.

Please try it again and tell me if it worked.

**Comment by priestjim** [comment]
It works now. Thanks!
